[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[program:tts]
environment=OTEL_SERVICE_NAME="%(ENV_VLLM_OTEL_SERVICE_NAME_TTS)s"
command=vllm serve Qwen/Qwen3-TTS-12Hz-1.7B-VoiceDesign --omni --host 0.0.0.0 --port 8001 --gpu-memory-utilization 0.40 --otlp-traces-endpoint=%(ENV_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT)s
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
autorestart=true

[program:chat]
environment=OTEL_SERVICE_NAME="%(ENV_VLLM_OTEL_SERVICE_NAME_CHAT)s"
command=vllm serve Qwen/Qwen3-0.6B --host 0.0.0.0 --port 8002 --gpu-memory-utilization 0.20 --max-model-len 8192 --otlp-traces-endpoint=%(ENV_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT)s
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
autorestart=true

[program:embedding]
environment=OTEL_SERVICE_NAME="%(ENV_VLLM_OTEL_SERVICE_NAME_EMBEDDING)s"
command=vllm serve Qwen/Qwen3-Embedding-0.6B --host 0.0.0.0 --port 8003 --gpu-memory-utilization 0.15 --max-model-len 8192 --otlp-traces-endpoint=%(ENV_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT)s
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
autorestart=true
