[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[inet_http_server]
port=0.0.0.0:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:tts]
environment=OTEL_SERVICE_NAME="%(ENV_VLLM_OTEL_SERVICE_NAME_TTS)s"
command=vllm serve Qwen/Qwen3-TTS-12Hz-1.7B-VoiceDesign --omni --host 0.0.0.0 --port 8001 --gpu-memory-utilization 0.65 --otlp-traces-endpoint=%(ENV_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT)s
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
autorestart=true
autostart=true
