/**
 * @fileoverview gRPC-Web generated client stub for screenplay
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.31.0
// source: screenplay.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as screenplay_pb from './screenplay_pb'; // proto import: "screenplay.proto"


export class ScreenplayServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorStreamImportStatus = new grpcWeb.MethodDescriptor(
    '/screenplay.ScreenplayService/StreamImportStatus',
    grpcWeb.MethodType.SERVER_STREAMING,
    screenplay_pb.StreamImportStatusRequest,
    screenplay_pb.ImportStatusEvent,
    (request: screenplay_pb.StreamImportStatusRequest) => {
      return request.serializeBinary();
    },
    screenplay_pb.ImportStatusEvent.deserializeBinary
  );

  streamImportStatus(
    request: screenplay_pb.StreamImportStatusRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<screenplay_pb.ImportStatusEvent> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/screenplay.ScreenplayService/StreamImportStatus',
      request,
      metadata || {},
      this.methodDescriptorStreamImportStatus);
  }

  methodDescriptorGetScreenplay = new grpcWeb.MethodDescriptor(
    '/screenplay.ScreenplayService/GetScreenplay',
    grpcWeb.MethodType.UNARY,
    screenplay_pb.GetScreenplayRequest,
    screenplay_pb.GetScreenplayResponse,
    (request: screenplay_pb.GetScreenplayRequest) => {
      return request.serializeBinary();
    },
    screenplay_pb.GetScreenplayResponse.deserializeBinary
  );

  getScreenplay(
    request: screenplay_pb.GetScreenplayRequest,
    metadata?: grpcWeb.Metadata | null): Promise<screenplay_pb.GetScreenplayResponse>;

  getScreenplay(
    request: screenplay_pb.GetScreenplayRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: screenplay_pb.GetScreenplayResponse) => void): grpcWeb.ClientReadableStream<screenplay_pb.GetScreenplayResponse>;

  getScreenplay(
    request: screenplay_pb.GetScreenplayRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: screenplay_pb.GetScreenplayResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/screenplay.ScreenplayService/GetScreenplay',
        request,
        metadata || {},
        this.methodDescriptorGetScreenplay,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/screenplay.ScreenplayService/GetScreenplay',
    request,
    metadata || {},
    this.methodDescriptorGetScreenplay);
  }

  methodDescriptorListScreenplays = new grpcWeb.MethodDescriptor(
    '/screenplay.ScreenplayService/ListScreenplays',
    grpcWeb.MethodType.UNARY,
    screenplay_pb.ListScreenplaysRequest,
    screenplay_pb.ListScreenplaysResponse,
    (request: screenplay_pb.ListScreenplaysRequest) => {
      return request.serializeBinary();
    },
    screenplay_pb.ListScreenplaysResponse.deserializeBinary
  );

  listScreenplays(
    request: screenplay_pb.ListScreenplaysRequest,
    metadata?: grpcWeb.Metadata | null): Promise<screenplay_pb.ListScreenplaysResponse>;

  listScreenplays(
    request: screenplay_pb.ListScreenplaysRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: screenplay_pb.ListScreenplaysResponse) => void): grpcWeb.ClientReadableStream<screenplay_pb.ListScreenplaysResponse>;

  listScreenplays(
    request: screenplay_pb.ListScreenplaysRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: screenplay_pb.ListScreenplaysResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/screenplay.ScreenplayService/ListScreenplays',
        request,
        metadata || {},
        this.methodDescriptorListScreenplays,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/screenplay.ScreenplayService/ListScreenplays',
    request,
    metadata || {},
    this.methodDescriptorListScreenplays);
  }

}

