/**
 * @fileoverview gRPC-Web generated client stub for content_generation
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.31.0
// source: content_generation.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as content_generation_pb from './content_generation_pb'; // proto import: "content_generation.proto"


export class ContentGenerationServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorStartRun = new grpcWeb.MethodDescriptor(
    '/content_generation.ContentGenerationService/StartRun',
    grpcWeb.MethodType.UNARY,
    content_generation_pb.StartRunRequest,
    content_generation_pb.StartRunResponse,
    (request: content_generation_pb.StartRunRequest) => {
      return request.serializeBinary();
    },
    content_generation_pb.StartRunResponse.deserializeBinary
  );

  startRun(
    request: content_generation_pb.StartRunRequest,
    metadata?: grpcWeb.Metadata | null): Promise<content_generation_pb.StartRunResponse>;

  startRun(
    request: content_generation_pb.StartRunRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: content_generation_pb.StartRunResponse) => void): grpcWeb.ClientReadableStream<content_generation_pb.StartRunResponse>;

  startRun(
    request: content_generation_pb.StartRunRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: content_generation_pb.StartRunResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/content_generation.ContentGenerationService/StartRun',
        request,
        metadata || {},
        this.methodDescriptorStartRun,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/content_generation.ContentGenerationService/StartRun',
    request,
    metadata || {},
    this.methodDescriptorStartRun);
  }

  methodDescriptorCompleteVoiceDetermination = new grpcWeb.MethodDescriptor(
    '/content_generation.ContentGenerationService/CompleteVoiceDetermination',
    grpcWeb.MethodType.UNARY,
    content_generation_pb.CompleteVoiceDeterminationRequest,
    content_generation_pb.CompleteVoiceDeterminationResponse,
    (request: content_generation_pb.CompleteVoiceDeterminationRequest) => {
      return request.serializeBinary();
    },
    content_generation_pb.CompleteVoiceDeterminationResponse.deserializeBinary
  );

  completeVoiceDetermination(
    request: content_generation_pb.CompleteVoiceDeterminationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<content_generation_pb.CompleteVoiceDeterminationResponse>;

  completeVoiceDetermination(
    request: content_generation_pb.CompleteVoiceDeterminationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: content_generation_pb.CompleteVoiceDeterminationResponse) => void): grpcWeb.ClientReadableStream<content_generation_pb.CompleteVoiceDeterminationResponse>;

  completeVoiceDetermination(
    request: content_generation_pb.CompleteVoiceDeterminationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: content_generation_pb.CompleteVoiceDeterminationResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/content_generation.ContentGenerationService/CompleteVoiceDetermination',
        request,
        metadata || {},
        this.methodDescriptorCompleteVoiceDetermination,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/content_generation.ContentGenerationService/CompleteVoiceDetermination',
    request,
    metadata || {},
    this.methodDescriptorCompleteVoiceDetermination);
  }

  methodDescriptorReplayRun = new grpcWeb.MethodDescriptor(
    '/content_generation.ContentGenerationService/ReplayRun',
    grpcWeb.MethodType.UNARY,
    content_generation_pb.ReplayRunRequest,
    content_generation_pb.ReplayRunResponse,
    (request: content_generation_pb.ReplayRunRequest) => {
      return request.serializeBinary();
    },
    content_generation_pb.ReplayRunResponse.deserializeBinary
  );

  replayRun(
    request: content_generation_pb.ReplayRunRequest,
    metadata?: grpcWeb.Metadata | null): Promise<content_generation_pb.ReplayRunResponse>;

  replayRun(
    request: content_generation_pb.ReplayRunRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: content_generation_pb.ReplayRunResponse) => void): grpcWeb.ClientReadableStream<content_generation_pb.ReplayRunResponse>;

  replayRun(
    request: content_generation_pb.ReplayRunRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: content_generation_pb.ReplayRunResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/content_generation.ContentGenerationService/ReplayRun',
        request,
        metadata || {},
        this.methodDescriptorReplayRun,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/content_generation.ContentGenerationService/ReplayRun',
    request,
    metadata || {},
    this.methodDescriptorReplayRun);
  }

  methodDescriptorRegenerateNode = new grpcWeb.MethodDescriptor(
    '/content_generation.ContentGenerationService/RegenerateNode',
    grpcWeb.MethodType.UNARY,
    content_generation_pb.RegenerateNodeRequest,
    content_generation_pb.RegenerateNodeResponse,
    (request: content_generation_pb.RegenerateNodeRequest) => {
      return request.serializeBinary();
    },
    content_generation_pb.RegenerateNodeResponse.deserializeBinary
  );

  regenerateNode(
    request: content_generation_pb.RegenerateNodeRequest,
    metadata?: grpcWeb.Metadata | null): Promise<content_generation_pb.RegenerateNodeResponse>;

  regenerateNode(
    request: content_generation_pb.RegenerateNodeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: content_generation_pb.RegenerateNodeResponse) => void): grpcWeb.ClientReadableStream<content_generation_pb.RegenerateNodeResponse>;

  regenerateNode(
    request: content_generation_pb.RegenerateNodeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: content_generation_pb.RegenerateNodeResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/content_generation.ContentGenerationService/RegenerateNode',
        request,
        metadata || {},
        this.methodDescriptorRegenerateNode,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/content_generation.ContentGenerationService/RegenerateNode',
    request,
    metadata || {},
    this.methodDescriptorRegenerateNode);
  }

  methodDescriptorGetRunStatus = new grpcWeb.MethodDescriptor(
    '/content_generation.ContentGenerationService/GetRunStatus',
    grpcWeb.MethodType.UNARY,
    content_generation_pb.GetRunStatusRequest,
    content_generation_pb.GetRunStatusResponse,
    (request: content_generation_pb.GetRunStatusRequest) => {
      return request.serializeBinary();
    },
    content_generation_pb.GetRunStatusResponse.deserializeBinary
  );

  getRunStatus(
    request: content_generation_pb.GetRunStatusRequest,
    metadata?: grpcWeb.Metadata | null): Promise<content_generation_pb.GetRunStatusResponse>;

  getRunStatus(
    request: content_generation_pb.GetRunStatusRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: content_generation_pb.GetRunStatusResponse) => void): grpcWeb.ClientReadableStream<content_generation_pb.GetRunStatusResponse>;

  getRunStatus(
    request: content_generation_pb.GetRunStatusRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: content_generation_pb.GetRunStatusResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/content_generation.ContentGenerationService/GetRunStatus',
        request,
        metadata || {},
        this.methodDescriptorGetRunStatus,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/content_generation.ContentGenerationService/GetRunStatus',
    request,
    metadata || {},
    this.methodDescriptorGetRunStatus);
  }

  methodDescriptorGetLatestRunForScreenplay = new grpcWeb.MethodDescriptor(
    '/content_generation.ContentGenerationService/GetLatestRunForScreenplay',
    grpcWeb.MethodType.UNARY,
    content_generation_pb.GetLatestRunForScreenplayRequest,
    content_generation_pb.GetRunStatusResponse,
    (request: content_generation_pb.GetLatestRunForScreenplayRequest) => {
      return request.serializeBinary();
    },
    content_generation_pb.GetRunStatusResponse.deserializeBinary
  );

  getLatestRunForScreenplay(
    request: content_generation_pb.GetLatestRunForScreenplayRequest,
    metadata?: grpcWeb.Metadata | null): Promise<content_generation_pb.GetRunStatusResponse>;

  getLatestRunForScreenplay(
    request: content_generation_pb.GetLatestRunForScreenplayRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: content_generation_pb.GetRunStatusResponse) => void): grpcWeb.ClientReadableStream<content_generation_pb.GetRunStatusResponse>;

  getLatestRunForScreenplay(
    request: content_generation_pb.GetLatestRunForScreenplayRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: content_generation_pb.GetRunStatusResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/content_generation.ContentGenerationService/GetLatestRunForScreenplay',
        request,
        metadata || {},
        this.methodDescriptorGetLatestRunForScreenplay,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/content_generation.ContentGenerationService/GetLatestRunForScreenplay',
    request,
    metadata || {},
    this.methodDescriptorGetLatestRunForScreenplay);
  }

  methodDescriptorGetNodeAudio = new grpcWeb.MethodDescriptor(
    '/content_generation.ContentGenerationService/GetNodeAudio',
    grpcWeb.MethodType.UNARY,
    content_generation_pb.GetNodeAudioRequest,
    content_generation_pb.GetNodeAudioResponse,
    (request: content_generation_pb.GetNodeAudioRequest) => {
      return request.serializeBinary();
    },
    content_generation_pb.GetNodeAudioResponse.deserializeBinary
  );

  getNodeAudio(
    request: content_generation_pb.GetNodeAudioRequest,
    metadata?: grpcWeb.Metadata | null): Promise<content_generation_pb.GetNodeAudioResponse>;

  getNodeAudio(
    request: content_generation_pb.GetNodeAudioRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: content_generation_pb.GetNodeAudioResponse) => void): grpcWeb.ClientReadableStream<content_generation_pb.GetNodeAudioResponse>;

  getNodeAudio(
    request: content_generation_pb.GetNodeAudioRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: content_generation_pb.GetNodeAudioResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/content_generation.ContentGenerationService/GetNodeAudio',
        request,
        metadata || {},
        this.methodDescriptorGetNodeAudio,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/content_generation.ContentGenerationService/GetNodeAudio',
    request,
    metadata || {},
    this.methodDescriptorGetNodeAudio);
  }

  methodDescriptorStreamRunStatus = new grpcWeb.MethodDescriptor(
    '/content_generation.ContentGenerationService/StreamRunStatus',
    grpcWeb.MethodType.SERVER_STREAMING,
    content_generation_pb.StreamRunStatusRequest,
    content_generation_pb.RunStatusUpdate,
    (request: content_generation_pb.StreamRunStatusRequest) => {
      return request.serializeBinary();
    },
    content_generation_pb.RunStatusUpdate.deserializeBinary
  );

  streamRunStatus(
    request: content_generation_pb.StreamRunStatusRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<content_generation_pb.RunStatusUpdate> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/content_generation.ContentGenerationService/StreamRunStatus',
      request,
      metadata || {},
      this.methodDescriptorStreamRunStatus);
  }

  methodDescriptorListRunsForScreenplay = new grpcWeb.MethodDescriptor(
    '/content_generation.ContentGenerationService/ListRunsForScreenplay',
    grpcWeb.MethodType.UNARY,
    content_generation_pb.ListRunsForScreenplayRequest,
    content_generation_pb.ListRunsForScreenplayResponse,
    (request: content_generation_pb.ListRunsForScreenplayRequest) => {
      return request.serializeBinary();
    },
    content_generation_pb.ListRunsForScreenplayResponse.deserializeBinary
  );

  listRunsForScreenplay(
    request: content_generation_pb.ListRunsForScreenplayRequest,
    metadata?: grpcWeb.Metadata | null): Promise<content_generation_pb.ListRunsForScreenplayResponse>;

  listRunsForScreenplay(
    request: content_generation_pb.ListRunsForScreenplayRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: content_generation_pb.ListRunsForScreenplayResponse) => void): grpcWeb.ClientReadableStream<content_generation_pb.ListRunsForScreenplayResponse>;

  listRunsForScreenplay(
    request: content_generation_pb.ListRunsForScreenplayRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: content_generation_pb.ListRunsForScreenplayResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/content_generation.ContentGenerationService/ListRunsForScreenplay',
        request,
        metadata || {},
        this.methodDescriptorListRunsForScreenplay,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/content_generation.ContentGenerationService/ListRunsForScreenplay',
    request,
    metadata || {},
    this.methodDescriptorListRunsForScreenplay);
  }

  methodDescriptorGetRunDetails = new grpcWeb.MethodDescriptor(
    '/content_generation.ContentGenerationService/GetRunDetails',
    grpcWeb.MethodType.UNARY,
    content_generation_pb.GetRunDetailsRequest,
    content_generation_pb.GetRunDetailsResponse,
    (request: content_generation_pb.GetRunDetailsRequest) => {
      return request.serializeBinary();
    },
    content_generation_pb.GetRunDetailsResponse.deserializeBinary
  );

  getRunDetails(
    request: content_generation_pb.GetRunDetailsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<content_generation_pb.GetRunDetailsResponse>;

  getRunDetails(
    request: content_generation_pb.GetRunDetailsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: content_generation_pb.GetRunDetailsResponse) => void): grpcWeb.ClientReadableStream<content_generation_pb.GetRunDetailsResponse>;

  getRunDetails(
    request: content_generation_pb.GetRunDetailsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: content_generation_pb.GetRunDetailsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/content_generation.ContentGenerationService/GetRunDetails',
        request,
        metadata || {},
        this.methodDescriptorGetRunDetails,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/content_generation.ContentGenerationService/GetRunDetails',
    request,
    metadata || {},
    this.methodDescriptorGetRunDetails);
  }

}

