// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using ThePlot.Infrastructure;

#nullable disable

namespace Ultra.ThePlot.Infrastructure.Migrations
{
    [DbContext(typeof(ThePlotContext))]
    [Migration("20260324021035_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("theplot")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ThePlot.Core.Characters.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("Aliases")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("aliases");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("VoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("voice_id");

                    b.HasKey("Id")
                        .HasName("pk_characters");

                    b.HasIndex("VoiceId")
                        .HasDatabaseName("ix_characters_voice_id");

                    b.ToTable("characters", "theplot");

                    b.HasAnnotation("NoScope", true);
                });

            modelBuilder.Entity("ThePlot.Core.Locations.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.ToTable("locations", "theplot");

                    b.HasAnnotation("NoScope", true);
                });

            modelBuilder.Entity("ThePlot.Core.SceneElements.SceneElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<JsonDocument>("Content")
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_last_modified");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<JsonDocument>("PdfMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("pdf_metadata");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uuid")
                        .HasColumnName("scene_id");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_order");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_scene_elements");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_scene_elements_character_id");

                    b.HasIndex("DateCreated")
                        .HasDatabaseName("ix_scene_elements_date_created");

                    b.HasIndex("SceneId")
                        .HasDatabaseName("ix_scene_elements_scene_id");

                    b.ToTable("scene_elements", "theplot");

                    b.HasAnnotation("NoScope", true);
                });

            modelBuilder.Entity("ThePlot.Core.Scenes.Scene", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_last_modified");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("heading");

                    b.Property<string>("InteriorExterior")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("interior_exterior");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<JsonDocument>("PdfMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("pdf_metadata");

                    b.Property<Guid>("ScreenplayId")
                        .HasColumnType("uuid")
                        .HasColumnName("screenplay_id");

                    b.Property<string>("TimeOfDay")
                        .HasColumnType("text")
                        .HasColumnName("time_of_day");

                    b.HasKey("Id")
                        .HasName("pk_scenes");

                    b.HasIndex("DateCreated")
                        .HasDatabaseName("ix_scenes_date_created");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_scenes_location_id");

                    b.HasIndex("ScreenplayId")
                        .HasDatabaseName("ix_scenes_screenplay_id");

                    b.ToTable("scenes", "theplot");

                    b.HasAnnotation("NoScope", true);
                });

            modelBuilder.Entity("ThePlot.Core.ScreenplayImports.ScreenplayImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("BlobUploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blob_uploaded_at");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_last_modified");

                    b.Property<string>("ImportErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("import_error_message");

                    b.Property<DateTimeOffset?>("ImportFailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("import_failed_at");

                    b.Property<Guid?>("ScreenplayId")
                        .HasColumnType("uuid")
                        .HasColumnName("screenplay_id");

                    b.Property<string>("SourceBlobName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_blob_name");

                    b.Property<int?>("TotalPages")
                        .HasColumnType("integer")
                        .HasColumnName("total_pages");

                    b.Property<DateTimeOffset?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validated_at");

                    b.HasKey("Id")
                        .HasName("pk_screenplay_imports");

                    b.HasIndex("DateCreated")
                        .HasDatabaseName("ix_screenplay_imports_date_created");

                    b.HasIndex("ScreenplayId")
                        .HasDatabaseName("ix_screenplay_imports_screenplay_id");

                    b.HasIndex("SourceBlobName")
                        .HasDatabaseName("ix_screenplay_imports_source_blob_name");

                    b.ToTable("screenplay_imports", "theplot");

                    b.HasAnnotation("NoScope", true);
                });

            modelBuilder.Entity("ThePlot.Core.ScreenplayImports.ScreenplayImportChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_last_modified");

                    b.Property<int>("EndPage")
                        .HasColumnType("integer")
                        .HasColumnName("end_page");

                    b.Property<DateTimeOffset?>("ProcessCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("process_completed_at");

                    b.Property<string>("ProcessErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("process_error_message");

                    b.Property<string>("ProcessStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("process_status");

                    b.Property<Guid>("ScreenplayImportId")
                        .HasColumnType("uuid")
                        .HasColumnName("screenplay_import_id");

                    b.Property<DateTimeOffset?>("SplitCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("split_completed_at");

                    b.Property<string>("SplitErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("split_error_message");

                    b.Property<string>("SplitStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("split_status");

                    b.Property<int>("StartPage")
                        .HasColumnType("integer")
                        .HasColumnName("start_page");

                    b.HasKey("Id")
                        .HasName("pk_screenplay_import_chunks");

                    b.HasIndex("ScreenplayImportId")
                        .HasDatabaseName("ix_screenplay_import_chunks_screenplay_import_id");

                    b.HasIndex("ScreenplayImportId", "StartPage")
                        .IsUnique()
                        .HasDatabaseName("ix_screenplay_import_chunks_screenplay_import_id_start_page");

                    b.ToTable("screenplay_import_chunks", "theplot");

                    b.HasAnnotation("NoScope", true);
                });

            modelBuilder.Entity("ThePlot.Core.Screenplays.Screenplay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("Authors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("authors");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_deleted");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_last_modified");

                    b.Property<JsonDocument>("PdfMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("pdf_metadata");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_screenplays");

                    b.HasIndex("DateCreated")
                        .HasDatabaseName("ix_screenplays_date_created");

                    b.ToTable("screenplays", "theplot");

                    b.HasAnnotation("NoScope", true);
                });

            modelBuilder.Entity("ThePlot.Core.Voices.Voice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_voices");

                    b.ToTable("voices", "theplot");

                    b.HasAnnotation("NoScope", true);
                });

            modelBuilder.Entity("ThePlot.Core.Characters.Character", b =>
                {
                    b.HasOne("ThePlot.Core.Voices.Voice", "Voice")
                        .WithMany()
                        .HasForeignKey("VoiceId")
                        .HasConstraintName("fk_characters_voices_voice_id");

                    b.Navigation("Voice");
                });

            modelBuilder.Entity("ThePlot.Core.SceneElements.SceneElement", b =>
                {
                    b.HasOne("ThePlot.Core.Characters.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .HasConstraintName("fk_scene_elements_characters_character_id");

                    b.HasOne("ThePlot.Core.Scenes.Scene", "Scene")
                        .WithMany("SceneElements")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scene_elements_scenes_scene_id");

                    b.Navigation("Character");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("ThePlot.Core.Scenes.Scene", b =>
                {
                    b.HasOne("ThePlot.Core.Locations.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .HasConstraintName("fk_scenes_locations_location_id");

                    b.HasOne("ThePlot.Core.Screenplays.Screenplay", "Screenplay")
                        .WithMany("Scenes")
                        .HasForeignKey("ScreenplayId")
                        .HasConstraintName("fk_scenes_screenplays_screenplay_id");

                    b.Navigation("Location");

                    b.Navigation("Screenplay");
                });

            modelBuilder.Entity("ThePlot.Core.ScreenplayImports.ScreenplayImportChunk", b =>
                {
                    b.HasOne("ThePlot.Core.ScreenplayImports.ScreenplayImport", null)
                        .WithMany("Chunks")
                        .HasForeignKey("ScreenplayImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_screenplay_import_chunks_screenplay_imports_screenplay_impo");
                });

            modelBuilder.Entity("ThePlot.Core.Scenes.Scene", b =>
                {
                    b.Navigation("SceneElements");
                });

            modelBuilder.Entity("ThePlot.Core.ScreenplayImports.ScreenplayImport", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("ThePlot.Core.Screenplays.Screenplay", b =>
                {
                    b.Navigation("Scenes");
                });
#pragma warning restore 612, 618
        }
    }
}
