// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using ThePlot.Infrastructure;

#nullable disable

namespace ThePlot.Infrastructure.Migrations
{
    [DbContext(typeof(ThePlotContext))]
    partial class ThePlotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("theplot")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ThePlot.Core.Characters.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("Aliases")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("aliases");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("VoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("voice_id");

                    b.HasKey("Id")
                        .HasName("pk_characters");

                    b.HasIndex("VoiceId")
                        .HasDatabaseName("ix_characters_voice_id");

                    b.ToTable("characters", "theplot");

                    b.HasAnnotation("NoScope", true);
                });

            modelBuilder.Entity("ThePlot.Core.ContentGeneration.GeneratedArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_last_modified");

                    b.Property<Guid>("GenerationAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("generation_attempt_id");

                    b.Property<Guid>("GenerationNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("generation_node_id");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("MimeType")
                        .HasColumnType("text")
                        .HasColumnName("mime_type");

                    b.Property<string>("StorageUri")
                        .HasColumnType("text")
                        .HasColumnName("storage_uri");

                    b.HasKey("Id")
                        .HasName("pk_generated_artifacts");

                    b.HasIndex("GenerationAttemptId")
                        .HasDatabaseName("ix_generated_artifacts_generation_attempt_id");

                    b.HasIndex("GenerationNodeId", "IsCurrent")
                        .HasDatabaseName("ix_generated_artifacts_generation_node_id_is_current");

                    b.ToTable("generated_artifacts", "theplot");

                    b.HasAnnotation("NoScope", true);
                });

            modelBuilder.Entity("ThePlot.Core.ContentGeneration.GenerationAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<decimal>("Cost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("cost");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_last_modified");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid>("GenerationNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("generation_node_id");

                    b.Property<int>("InputAudioTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("input_audio_tokens");

                    b.Property<int>("InputTextTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("input_text_tokens");

                    b.Property<int>("OutputAudioTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("output_audio_tokens");

                    b.Property<int>("OutputTextTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("output_text_tokens");

                    b.Property<JsonDocument>("ProviderRequestJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("provider_request_json");

                    b.Property<JsonDocument>("ProviderResponseJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("provider_response_json");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_generation_attempts");

                    b.HasIndex("GenerationNodeId")
                        .HasDatabaseName("ix_generation_attempts_generation_node_id");

                    b.HasIndex("GenerationNodeId", "AttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_generation_attempts_generation_node_id_attempt_number");

                    b.ToTable("generation_attempts", "theplot");

                    b.HasAnnotation("NoScope", true);
                });

            modelBuilder.Entity("ThePlot.Core.ContentGeneration.GenerationEdge", b =>
                {
                    b.Property<Guid>("FromNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_node_id");

                    b.Property<Guid>("ToNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_node_id");

                    b.HasKey("FromNodeId", "ToNodeId")
                        .HasName("pk_generation_edges");

                    b.HasIndex("ToNodeId")
                        .HasDatabaseName("ix_generation_edges_to_node_id");

                    b.ToTable("generation_edges", "theplot");

                    b.HasAnnotation("NoScope", true);
                });

            modelBuilder.Entity("ThePlot.Core.ContentGeneration.GenerationNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("AnalysisResult")
                        .HasColumnType("jsonb")
                        .HasColumnName("analysis_result");

                    b.Property<Guid?>("CurrentAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_attempt_id");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_last_modified");

                    b.Property<Guid>("GenerationRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("generation_run_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("last_error_message");

                    b.Property<DateTime?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("LeaseWorkerId")
                        .HasColumnType("text")
                        .HasColumnName("lease_worker_id");

                    b.Property<JsonDocument>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTime?>("RunnableAfterUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("runnable_after_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_generation_nodes");

                    b.HasIndex("CurrentAttemptId")
                        .HasDatabaseName("ix_generation_nodes_current_attempt_id");

                    b.HasIndex("GenerationRunId")
                        .HasDatabaseName("ix_generation_nodes_generation_run_id");

                    b.HasIndex("GenerationRunId", "Status", "RunnableAfterUtc")
                        .HasDatabaseName("ix_generation_nodes_generation_run_id_status_runnable_after_utc");

                    b.ToTable("generation_nodes", "theplot");

                    b.HasAnnotation("NoScope", true);
                });

            modelBuilder.Entity("ThePlot.Core.ContentGeneration.GenerationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_last_modified");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phase");

                    b.Property<Guid>("ScreenplayId")
                        .HasColumnType("uuid")
                        .HasColumnName("screenplay_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TraceParent")
                        .HasColumnType("text")
                        .HasColumnName("trace_parent");

                    b.HasKey("Id")
                        .HasName("pk_generation_runs");

                    b.HasIndex("ScreenplayId")
                        .HasDatabaseName("ix_generation_runs_screenplay_id");

                    b.HasIndex("ScreenplayId", "Status")
                        .HasDatabaseName("ix_generation_runs_screenplay_id_status");

                    b.ToTable("generation_runs", "theplot");

                    b.HasAnnotation("NoScope", true);
                });

            modelBuilder.Entity("ThePlot.Core.Locations.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.ToTable("locations", "theplot");

                    b.HasAnnotation("NoScope", true);
                });

            modelBuilder.Entity("ThePlot.Core.SceneElements.SceneElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<JsonDocument>("Content")
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_last_modified");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<JsonDocument>("PdfMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("pdf_metadata");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uuid")
                        .HasColumnName("scene_id");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_order");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_scene_elements");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_scene_elements_character_id");

                    b.HasIndex("DateCreated")
                        .HasDatabaseName("ix_scene_elements_date_created");

                    b.HasIndex("SceneId")
                        .HasDatabaseName("ix_scene_elements_scene_id");

                    b.ToTable("scene_elements", "theplot");

                    b.HasAnnotation("NoScope", true);
                });

            modelBuilder.Entity("ThePlot.Core.Scenes.Scene", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_last_modified");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("heading");

                    b.Property<string>("InteriorExterior")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("interior_exterior");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<JsonDocument>("PdfMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("pdf_metadata");

                    b.Property<Guid>("ScreenplayId")
                        .HasColumnType("uuid")
                        .HasColumnName("screenplay_id");

                    b.Property<string>("TimeOfDay")
                        .HasColumnType("text")
                        .HasColumnName("time_of_day");

                    b.HasKey("Id")
                        .HasName("pk_scenes");

                    b.HasIndex("DateCreated")
                        .HasDatabaseName("ix_scenes_date_created");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_scenes_location_id");

                    b.HasIndex("ScreenplayId")
                        .HasDatabaseName("ix_scenes_screenplay_id");

                    b.ToTable("scenes", "theplot");

                    b.HasAnnotation("NoScope", true);
                });

            modelBuilder.Entity("ThePlot.Core.ScreenplayImports.ScreenplayImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("BlobUploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blob_uploaded_at");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_last_modified");

                    b.Property<string>("ImportErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("import_error_message");

                    b.Property<DateTimeOffset?>("ImportFailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("import_failed_at");

                    b.Property<Guid?>("ScreenplayId")
                        .HasColumnType("uuid")
                        .HasColumnName("screenplay_id");

                    b.Property<string>("SourceBlobName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_blob_name");

                    b.Property<int?>("TotalPages")
                        .HasColumnType("integer")
                        .HasColumnName("total_pages");

                    b.Property<DateTimeOffset?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validated_at");

                    b.HasKey("Id")
                        .HasName("pk_screenplay_imports");

                    b.HasIndex("DateCreated")
                        .HasDatabaseName("ix_screenplay_imports_date_created");

                    b.HasIndex("ScreenplayId")
                        .HasDatabaseName("ix_screenplay_imports_screenplay_id");

                    b.HasIndex("SourceBlobName")
                        .HasDatabaseName("ix_screenplay_imports_source_blob_name");

                    b.ToTable("screenplay_imports", "theplot");

                    b.HasAnnotation("NoScope", true);
                });

            modelBuilder.Entity("ThePlot.Core.ScreenplayImports.ScreenplayImportChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_last_modified");

                    b.Property<int>("EndPage")
                        .HasColumnType("integer")
                        .HasColumnName("end_page");

                    b.Property<DateTimeOffset?>("ProcessCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("process_completed_at");

                    b.Property<string>("ProcessErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("process_error_message");

                    b.Property<string>("ProcessStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("process_status");

                    b.Property<Guid>("ScreenplayImportId")
                        .HasColumnType("uuid")
                        .HasColumnName("screenplay_import_id");

                    b.Property<DateTimeOffset?>("SplitCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("split_completed_at");

                    b.Property<string>("SplitErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("split_error_message");

                    b.Property<string>("SplitStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("split_status");

                    b.Property<int>("StartPage")
                        .HasColumnType("integer")
                        .HasColumnName("start_page");

                    b.HasKey("Id")
                        .HasName("pk_screenplay_import_chunks");

                    b.HasIndex("ScreenplayImportId")
                        .HasDatabaseName("ix_screenplay_import_chunks_screenplay_import_id");

                    b.HasIndex("ScreenplayImportId", "StartPage")
                        .IsUnique()
                        .HasDatabaseName("ix_screenplay_import_chunks_screenplay_import_id_start_page");

                    b.ToTable("screenplay_import_chunks", "theplot");

                    b.HasAnnotation("NoScope", true);
                });

            modelBuilder.Entity("ThePlot.Core.Screenplays.Screenplay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("Authors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("authors");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_deleted");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_last_modified");

                    b.Property<JsonDocument>("PdfMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("pdf_metadata");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_screenplays");

                    b.HasIndex("DateCreated")
                        .HasDatabaseName("ix_screenplays_date_created");

                    b.ToTable("screenplays", "theplot");

                    b.HasAnnotation("NoScope", true);
                });

            modelBuilder.Entity("ThePlot.Core.Voices.Voice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AudioBlobUri")
                        .HasColumnType("text")
                        .HasColumnName("audio_blob_uri");

                    b.Property<JsonDocument>("AudioMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("audio_metadata");

                    b.Property<string>("AudioMimeType")
                        .HasColumnType("text")
                        .HasColumnName("audio_mime_type");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_last_modified");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_normalized");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("ScreenplayId")
                        .HasColumnType("uuid")
                        .HasColumnName("screenplay_id");

                    b.HasKey("Id")
                        .HasName("pk_voices");

                    b.HasIndex("ScreenplayId")
                        .HasDatabaseName("ix_voices_screenplay_id");

                    b.HasIndex("ScreenplayId", "NameNormalized")
                        .IsUnique()
                        .HasDatabaseName("ix_voices_screenplay_id_name_normalized");

                    b.ToTable("voices", "theplot");

                    b.HasAnnotation("NoScope", true);
                });

            modelBuilder.Entity("ThePlot.Core.Characters.Character", b =>
                {
                    b.HasOne("ThePlot.Core.Voices.Voice", "Voice")
                        .WithMany()
                        .HasForeignKey("VoiceId")
                        .HasConstraintName("fk_characters_voices_voice_id");

                    b.Navigation("Voice");
                });

            modelBuilder.Entity("ThePlot.Core.ContentGeneration.GeneratedArtifact", b =>
                {
                    b.HasOne("ThePlot.Core.ContentGeneration.GenerationAttempt", "GenerationAttempt")
                        .WithMany("Artifacts")
                        .HasForeignKey("GenerationAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_generated_artifacts_generation_attempts_generation_attempt_");

                    b.HasOne("ThePlot.Core.ContentGeneration.GenerationNode", "GenerationNode")
                        .WithMany("Artifacts")
                        .HasForeignKey("GenerationNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_generated_artifacts_generation_nodes_generation_node_id");

                    b.Navigation("GenerationAttempt");

                    b.Navigation("GenerationNode");
                });

            modelBuilder.Entity("ThePlot.Core.ContentGeneration.GenerationAttempt", b =>
                {
                    b.HasOne("ThePlot.Core.ContentGeneration.GenerationNode", "GenerationNode")
                        .WithMany("Attempts")
                        .HasForeignKey("GenerationNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_generation_attempts_generation_nodes_generation_node_id");

                    b.Navigation("GenerationNode");
                });

            modelBuilder.Entity("ThePlot.Core.ContentGeneration.GenerationEdge", b =>
                {
                    b.HasOne("ThePlot.Core.ContentGeneration.GenerationNode", "FromNode")
                        .WithMany("OutgoingEdges")
                        .HasForeignKey("FromNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_generation_edges_generation_nodes_from_node_id");

                    b.HasOne("ThePlot.Core.ContentGeneration.GenerationNode", "ToNode")
                        .WithMany("IncomingEdges")
                        .HasForeignKey("ToNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_generation_edges_generation_nodes_to_node_id");

                    b.Navigation("FromNode");

                    b.Navigation("ToNode");
                });

            modelBuilder.Entity("ThePlot.Core.ContentGeneration.GenerationNode", b =>
                {
                    b.HasOne("ThePlot.Core.ContentGeneration.GenerationAttempt", "CurrentAttempt")
                        .WithMany()
                        .HasForeignKey("CurrentAttemptId")
                        .HasConstraintName("fk_generation_nodes_generation_attempts_current_attempt_id");

                    b.HasOne("ThePlot.Core.ContentGeneration.GenerationRun", "GenerationRun")
                        .WithMany("Nodes")
                        .HasForeignKey("GenerationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_generation_nodes_generation_runs_generation_run_id");

                    b.Navigation("CurrentAttempt");

                    b.Navigation("GenerationRun");
                });

            modelBuilder.Entity("ThePlot.Core.ContentGeneration.GenerationRun", b =>
                {
                    b.HasOne("ThePlot.Core.Screenplays.Screenplay", "Screenplay")
                        .WithMany("GenerationRuns")
                        .HasForeignKey("ScreenplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_generation_runs_screenplays_screenplay_id");

                    b.Navigation("Screenplay");
                });

            modelBuilder.Entity("ThePlot.Core.SceneElements.SceneElement", b =>
                {
                    b.HasOne("ThePlot.Core.Characters.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .HasConstraintName("fk_scene_elements_characters_character_id");

                    b.HasOne("ThePlot.Core.Scenes.Scene", "Scene")
                        .WithMany("SceneElements")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scene_elements_scenes_scene_id");

                    b.Navigation("Character");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("ThePlot.Core.Scenes.Scene", b =>
                {
                    b.HasOne("ThePlot.Core.Locations.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .HasConstraintName("fk_scenes_locations_location_id");

                    b.HasOne("ThePlot.Core.Screenplays.Screenplay", "Screenplay")
                        .WithMany("Scenes")
                        .HasForeignKey("ScreenplayId")
                        .HasConstraintName("fk_scenes_screenplays_screenplay_id");

                    b.Navigation("Location");

                    b.Navigation("Screenplay");
                });

            modelBuilder.Entity("ThePlot.Core.ScreenplayImports.ScreenplayImportChunk", b =>
                {
                    b.HasOne("ThePlot.Core.ScreenplayImports.ScreenplayImport", null)
                        .WithMany("Chunks")
                        .HasForeignKey("ScreenplayImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_screenplay_import_chunks_screenplay_imports_screenplay_impo");
                });

            modelBuilder.Entity("ThePlot.Core.Voices.Voice", b =>
                {
                    b.HasOne("ThePlot.Core.Screenplays.Screenplay", "Screenplay")
                        .WithMany("Voices")
                        .HasForeignKey("ScreenplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_voices_screenplays_screenplay_id");

                    b.Navigation("Screenplay");
                });

            modelBuilder.Entity("ThePlot.Core.ContentGeneration.GenerationAttempt", b =>
                {
                    b.Navigation("Artifacts");
                });

            modelBuilder.Entity("ThePlot.Core.ContentGeneration.GenerationNode", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("Attempts");

                    b.Navigation("IncomingEdges");

                    b.Navigation("OutgoingEdges");
                });

            modelBuilder.Entity("ThePlot.Core.ContentGeneration.GenerationRun", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("ThePlot.Core.Scenes.Scene", b =>
                {
                    b.Navigation("SceneElements");
                });

            modelBuilder.Entity("ThePlot.Core.ScreenplayImports.ScreenplayImport", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("ThePlot.Core.Screenplays.Screenplay", b =>
                {
                    b.Navigation("GenerationRuns");

                    b.Navigation("Scenes");

                    b.Navigation("Voices");
                });
#pragma warning restore 612, 618
        }
    }
}
