/**
 * @fileoverview gRPC-Web generated client stub for upload
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.31.0
// source: upload.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as upload_pb from './upload_pb'; // proto import: "upload.proto"


export class UploadClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorRequestUploadToken = new grpcWeb.MethodDescriptor(
    '/upload.Upload/RequestUploadToken',
    grpcWeb.MethodType.UNARY,
    upload_pb.UploadTokenRequest,
    upload_pb.UploadTokenResponse,
    (request: upload_pb.UploadTokenRequest) => {
      return request.serializeBinary();
    },
    upload_pb.UploadTokenResponse.deserializeBinary
  );

  requestUploadToken(
    request: upload_pb.UploadTokenRequest,
    metadata?: grpcWeb.Metadata | null): Promise<upload_pb.UploadTokenResponse>;

  requestUploadToken(
    request: upload_pb.UploadTokenRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: upload_pb.UploadTokenResponse) => void): grpcWeb.ClientReadableStream<upload_pb.UploadTokenResponse>;

  requestUploadToken(
    request: upload_pb.UploadTokenRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: upload_pb.UploadTokenResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/upload.Upload/RequestUploadToken',
        request,
        metadata || {},
        this.methodDescriptorRequestUploadToken,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/upload.Upload/RequestUploadToken',
    request,
    metadata || {},
    this.methodDescriptorRequestUploadToken);
  }

}

