receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:${env:OTLP_GRPC_PORT}
      http:
        endpoint: 0.0.0.0:${env:OTLP_HTTP_PORT}

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  otlp/aspire:
    endpoint: ${env:OTEL_EXPORTER_OTLP_ENDPOINT}
    headers:
      x-otlp-api-key: ${env:ASPIRE_API_KEY}
    tls:
      insecure: ${env:ASPIRE_INSECURE}
      insecure_skip_verify: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/aspire]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/aspire]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/aspire]
